# Generated by Django 4.2.1 on 2023-05-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserForm',
        ),
    ]
