# Generated by Django 4.2.1 on 2023-05-21 08:58

from django.db import migrations, models
import user_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_form', '0002_rename_user_userform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='userform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[user_form.models.validate_phone_number]),
        ),
    ]
